---
- hosts: all
  become: yes
  tasks:
  - name: install jdk
    apt:
     name: openjdk-8-jre 
     state: present
    when: ansible_os_family =="Debian"

  - name: install jdk in linux servce
    yum: 
     name: java-1.8.0-openjdk
     state: present
    when: ansible_os_family =="RedHat"