---
- hosts: all
  become: yes
  tasks:

  - include_tasks: file.yml
  - name: sfdfgdfg
    apt:
     name: apache2
     state: present
     notify: papa

  - name: rfsfddf
    template:
     src: fdfg
     dest: dfbdfb
    notify: papa
  handlers:
  - name: papa
    service:
     name: apache2
     state: started
    